const jsonProducts = [
  {
      "id": "12b5f298-942d-4c7a-87a8-1c4cbe0a7755",
      "name": "JERSEY LOCAL SELECCIÓN ESTADOS UNIDOS 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
          {"size" : "S", "stock":20},
          {"size" : "M", "stock":20},
          {"size" : "L", "stock":20},
          {"size" : "XL", "stock":20},
        ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665599696/usalocal_1024x1024_tpcudq.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "d33ee78e-50ab-4268-bc04-1db0e2809562",
      "name": "JERSEY VISITANTE SELECCIÓN IRAN 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665612582/632985-ir-c3-a1n-202_wtvgzq.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "64cbdee6-5048-4b2c-86fe-33d8a0b8827f",
      "name": "JERSEY LOCAL SELECCIÓN URUGUAY 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665598444/P55A6JUJ6ZDY7NS7VMGAWHUTEM_ttc5lp.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "54d50f05-7e55-4875-9090-78fae7b051ee",
      "name": "JERSEY VISITANTE SELECCIÓN URUGUAY 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665598463/RCOUO4INXVB4ROOSR7375KHA24_btlfjz.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "f74425f2-1c89-4140-abbe-f62a73eead79",
      "name": "JERSEY LOCAL SELECCIÓN ECUADOR 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665594855/HA4WAYR2LZCSZMHMK3S743TY4E_jdez3y.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "fe73e7a3-a844-4e19-aca6-f8fa9d1f181b",
      "name": "JERSEY LOCAL SELECCIÓN IRAN 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665612563/632985-ir-c3-a1n-201_qxtgpm.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "ee4eb652-daab-4a3f-8cfc-bb71ffd62e46",
      "name": "JERSEY VISITANTE SELECCIÓN SENEGAL 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596193/G6RFRDXWBZBLVOJTDGJBHYQMYM_gnqy6k.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "a483a846-1e42-46a7-b583-f1d4a57e77f2",
      "name": "JERSEY LOCAL SELECCIÓN GALES 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665612414/WC2022-13_anuwbn.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "f445e4cf-8f8e-4c3b-9c02-dafbc1cc053e",
      "name": "JERSEY LOCAL SELECCIÓN DINAMARCA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665600748/aaaadinamarc_1024x1024_tttjuk.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "8f298461-066b-41db-8fdb-449dd3639bbf",
      "name": "JERSEY LOCAL SELECCIÓN COSTA RICA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665610746/Camisetas-Costa-Rica-2022_oegxov.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "bf9bf185-52d1-4b81-9169-7ea67ee41b5d",
      "name": "JERSEY VISITANTE SELECCIÓN ESTADOS UNIDOS 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665599753/usavisi_1024x1024_ho2w2s.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "2826948b-68f3-41e8-b2dd-b42728362a7b",
      "name": "JERSEY UNIFORME DE VISITANTE ALEMANIA 22",
      "price": 1499,
      "detail": "Inspirado en los colores de la bandera del país, este jersey visitante adidas para jóvenes distorsiona la D de Deutschland para reflejar el dinamismo del equipo actual. Enfocado en mantener los hinchas orgullosos y cómodos, este jersey incluye details tejidos del equipo y tecnología de absorción AEROREADY.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665517437/Jersey_Uniforme_de_Visitante_Alemania_22_Negro_HF1469_01_laydown_st9xop.jpg",
      "stars": 3,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "d42f21a8-6b9f-44bd-945f-2c8a1175fadc",
      "name": "JERSEY TERCERO SELECCIÓN MEXICO 22",
      "price": 1799,
      "detail": "JERSEY TERCERO",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665603369/mexicoooter_1024x1024_pernpp.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "ac5cab3c-e376-4e36-a1e4-9c996fb3377d",
      "name": "JERSEY LOCAL SELECCIÓN POLONIA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665600498/polonialocal_1024x1024_lowcky.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "e5aac51d-d580-4710-864b-8b22814e3a41",
      "name": "JERSEY LOCAL SELECCIÓN MARRUECOS 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596731/Y7772DAWPFCYLK6NXQJGA774OY_jtmlmv.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "1576fbaa-3233-458f-8a20-8e14f30d3793",
      "name": "JERSEY LOCAL SELECCIÓN ARABIA SAUDITA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605772/arabiasauditalocal_1024x1024_umtvay.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "731b5554-5ea1-465e-a3c9-b6d053b49d10",
      "name": "JERSEY VISITANTE SELECCIÓN BRASIL 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596974/WLJJEPJR2VGUTA2T4WVNSHIIME_qdwe6q.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "bdf92743-9afd-418d-bff4-e26b3ad23a5c",
      "name": "JERSEY LOCAL SELECCIÓN TUNEZ 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665611360/camisetas-kappa-tunez-2022-3_pzrqgp.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "ace5cb81-e99a-4ca0-9b2e-25bf9f9fb4da",
      "name": "JERSEY LOCAL SELECCIÓN GHANA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665598695/XOKFNAUU6BE3BMD2VIIH2EOICE_zaiovp.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "07b7453b-42ae-4046-88d1-023d155c2eac",
      "name": "JERSEY LOCAL SELECCIÓN SUIZA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665598043/GN3CU77AZBC6HDJTRWURHSPSNU_a0rrbz.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "b2000f87-a59d-4b93-b2ee-c63af484ab53",
      "name": "SHORTS LOCAL SELECCIÓN NACIONAL DE MÉXICO",
      "price": 1099,
      "detail": "La tecnología AEROREADY ayuda a mantener tu cuerpo seco sin importar si estás preparándote para jugar o descansando en un día cálido. El escudo tejido en la pierna simboliza un nuevo comienzo.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665529898/Shorts_Local_Seleccion_Nacional_de_Mexico_Blanco_HD9315_21_model_bzxhw4.jpg",
      "stars": 5,
      "visible": true,
      "category": "Short",
  },
  {
      "id": "7b5d8272-771b-4ad2-a6a1-8d05cee4ce4e",
      "name": "JERSEY LOCAL SELECCIÓN BRASIL 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596958/LPU7XW4HXNF2PM7I36T2XFDSUE_hjkyjz.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey" ,
  },
  {
      "id": "34cc5aff-218c-4d52-b245-37abb30485f6",
      "name": "JERSEY DE LOCAL ARGENTINA 22",
      "price": 1799,
      "detail": "100% Argentina. A lo largo de la historia del fútbol, estas tres rayas azules han representado un juego de pies hipnotizante y un compromiso incomparable. Para el nuevo jersey de local de la Selección, adidas regresó a ese look ganador. Diseñado para hinchas, ofrece comodidad en todo momento gracias a su tejido suave con tecnología de absorción AEROREADY. Los details en la parte interior trasera del cuello están inspirados en la bandera nacional que los jugadores representan con tanto orgullo.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665597680/Jersey_de_Local_Argentina_22_Blanco_HF1495_01_laydown_nohfhc_oenfia.jpg",
      "stars": 4,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "88e26f6d-c0c8-436f-b322-ca3718125b5d",
      "name": "JERSEY LOCAL SELECCIÓN FRANCIA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665604059/francialo_1024x1024_s55go1.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "1cf9ed62-0472-47c4-9f5d-53c65ef75a3b",
      "name": "CALZADO DE FÚTBOL X SPEEDPORTAL MESSI.4 PASTO SINTÉTICO",
      "price": 1599,
      "detail": "Este calzado de fútbol fue creado para realizar movimientos rápidos y cambios de velocidad en superficies de césped artificial. Suave y resistente, su exterior textil revestido te ayuda a mantener el balón bajo tu control. Los estampados llamativos destacan el amor que Lionel Messi tiene con el balón. Hecho a base de materiales reciclados, el exterior incorpora al menos un 50 % de contenido reciclado. Este producto representa solo una de nuestras soluciones para acabar con los residuos plásticos.",
      "size-stock": [
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
        {"size" : "6", "stock":20},
        {"size" : "7", "stock":20},
        {"size" : "8", "stock":20},
        {"size" : "9", "stock":20},
        {"size" : "10", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665524632/Calzado_de_Futbol_X_Speedportal_Messi.4_Pasto_Sintetico_Blanco_GW8401_22_model_d6znav.jpg",
      "stars": 3,
      "visible": true,
      "category": "Calzado",
  },
  {
      "id": "f0eb1291-632d-4949-b122-79e4edeec2e7",
      "name": "JERSEY VISITANTE SELECCIÓN SERBIA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665597378/LYDPTD63AVCBDKNJ7WFQPWP2YU_e3nd1u.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "8aea730c-7e9e-4427-96ac-e2cd3c541b78",
      "name": "JERSEY VISITANTE SELECCIÓN CANADA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665603305/nike-canada-soccer-vapor-knit-iii-authentic-away-jersey-202122_1024x1024_flr7li.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "f3d948ef-0529-436e-9476-e53b8bf761d6",
      "name": "JERSEY VISITANTE SELECCIÓN ARABIA SAUDITA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605791/arabiasauditavisitante_1024x1024_bnwwmn.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "3238e67b-9bfb-4695-8419-ee14c1f42410",
      "name": "JERSEY LOCAL SELECCIÓN SERBIA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665597360/CRDEFOI2QRBPJGXYE52MZ6QL2E_g5jxrj.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "2bb6c7ee-ffad-4505-94ad-601618044bf8",
      "name": "JERSEY VISITANTE SELECCIÓN NACIONAL DE MÉXICO",
      "price": 1499,
      "detail": "100% Mexicano. Inspirado en civilizaciones antiguas, este jersey de visitante de México reune el espíritu de lucha necesario para dominar el mundo del fútbol. En medio de ese llamativo diseño, un detail al exterior del cuello muestra el cuerpo de serpiente de Quetzalcoatl, símbolo de las capacidades físicas de la humanidad. Los paneles de malla y el tejido absorbente de la tecnología AEROREADY se encargan de mantenerte cómodo y fresco en todo momento.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665597934/D_NQ_NP_2X_960925-MLM51235127866_082022-F_x22ndm_i5efwe.webp",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "7899a7eb-9cdb-49bc-bb4f-6208ddb54596",
      "name": "CONJUNTO LOCAL SELECCIÓN NACIONAL DE MÉXICO",
      "price": 1399,
      "detail": "El tejido suave con tecnología de absorción AEROREADY se encarga de brindar comodidad mientras viven sus sueños futboleros.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665597849/D_NQ_NP_714845-MLM50636648042_072022-O_vx6h9c_ufvw72.webp",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "31023b20-32b3-48b4-b314-52ebc7f6f598",
      "name": "JERSEY VISITANTE SELECCIÓN MARRUECOS 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596754/LIARZ3PLONA3JCPP6R4O6E5DSQ_svqufa.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "608b4b3b-7ca4-43a2-8827-482d12e89755",
      "name": "JERSEY LOCAL SELECCIÓN COREA DEL SUR 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605101/corealocal_1024x1024_je3pnx.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "f5433e01-2d25-45d2-9c00-fdde5a0dc307",
      "name": "MINIBALÓN AL RIHLA",
      "price": 349,
      "detail": "Al Rihla significa El Viaje, el balón es solo el comienzo. El resto de tu historia futbolística aún no está escrito. Inspirado en el diseño del balón oficial para partidos de la Copa Mundial de la FIFA™, este minibalón adidas Al Rihla te permite llevar tus habilidades futbolísticas a donde vayas. Su tamaño compacto y su interior de espuma lo hacen perfecto para los espacios reducidos y nunca tendrás que preocuparte por inflarlo.",
      "size-stock": [
        {"size" : "1", "stock":20},
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665528971/Minibalon_Al_Rihla_Blanco_H57793_01_standard_beirid.jpg",
      "stars": 5,
      "visible": true,
      "category": "Balon",
  },
  {
      "id": "bf289180-d974-470f-abd9-987ea2ba1edc",
      "name": "SHORTS UNIFORME LOCAL ARGENTINA 22",
      "price": 1099,
      "detail": "Parte de su uniforme local atemporal. Luciendo los clásicos colores blanco y negro, estos shorts de fútbol adidas de la Selección Argentina siguen el ejemplo del jersey al que acompañan. Creados para mantener cómodo al seguidor, están hechos de tejido suave y cuentan con tecnología de absorción AEROREADY. EL logo de la selección bordado le pone el toque final al diseño.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665529220/Shorts_Uniforme_Local_Argentina_22_Negro_HB9216_21_model_jdopxw.jpg",
      "stars": 4,
      "visible": true,
      "category": "Short",
  },
  {
      "id": "d4d2f25e-2d62-4484-a0ba-e62aa7229fca",
      "name": "BALÓN AL RIHLA PRO",
      "price": 4099,
      "detail": "Al Rihla significa El Viaje, el balón es solo el comienzo. El resto de tu historia futbolística aún no está escrito. El balón oficial de la Copa Mundial de la FIFA Qatar 2022™, este balón adidas Al Rihla Pro sin costuras lleva la precisión a nuevas alturas. La forma de la estructura Speedshell inspirada en el dhow se combina con textura y grabado de diamante para mejorar el efecto de giro y la precisión. Los estampados vibrantes brillan bajo un acabado perlado.",
      "size-stock": [
        {"size" : "1", "stock":20},
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665528805/Balon_Al_Rihla_Pro_Blanco_H57783_01_standard_a3u0bm.jpg",
      "stars": 5,
      "visible": true,
      "category": "Balon",
  },
  {
      "id": "91113e63-13b7-4add-9b6e-8c3b4ab6933a",
      "name": "BALÓN DE ENTRENAMIENTO AL RIHLA",
      "price": 749,
      "detail": "Al Rihla significa El Viaje, el balón es solo el comienzo. El resto de tu historia futbolística aún no está escrito. Inspirado en el look del balón oficial para partidos de la Copa Mundial de la FIFA™, este balón de entrenamiento Al Rihla de adidas es ideal para sesiones intensas. Su estructura cosida a máquina y la cámara de butilo garantizan resistencia y longevidad. La superficie texturizada le da el acabado perfecto.",
      "size-stock": [
        {"size" : "1", "stock":20},
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665528918/Balon_de_Entrenamiento_Al_Rihla_Blanco_H57798_01_standard_mrgtu8.jpg",
      "stars": 5,
      "visible": true,
      "category": "Balon",
  },
  {
      "id": "c8ae6f39-0ab9-4d24-a70c-0193d33c3548",
      "name": "JERSEY UNIFORME DE VISITANTE ESPAÑA 22",
      "price": 1499,
      "detail": "Listo para conquistar el mundo. El estampado ondulado de este jersey adidas para jóvenes se inspira en el logo de estilo art déco que recibió a los mejores futbolistas en España en 1982. En el centro del pecho se destacan las versiones tejidas del logo de las 3 Franjas y el escudo actualizado de la Selección de España. Creado para envolver los hinchas en comodidad, este jersey incorpora tecnología de absorción AEROREADY y paneles en la malla.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665517309/Jersey_Uniforme_de_Visitante_Espana_22_Azul_HF1405_01_laydown_sl4jrk.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "5f1342ac-df11-4a52-adb8-64aa1d7d749f",
      "name": "JERSEY LOCAL SELECCIÓN QATAR 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665602060/qatar_1024x1024_wsbzru.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "471cc932-5255-444d-b2cd-02b2365e9726",
      "name": "BALÓN DE ENTRENAMIENTO HOLOGRAMA AL RIHLA",
      "price": 849,
      "detail": "Al Rihla significa El Viaje, el balón es solo el comienzo. El resto de tu historia futbolística aún no está escrito. Inspirado en el look del balón oficial para partidos de la Copa Mundial de la FIFA™, este balón de entrenamiento Al Rihla de adidas es ideal para sesiones intensas. Su estructura cosida a máquina y la cámara de butilo garantizan resistencia y longevidad. La capa con holograma metalizado llama la atención en todo momento y lugar.",
      "size-stock": [
        {"size" : "1", "stock":20},
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665524766/Balon_de_Entrenamiento_Holograma_Al_Rihla_Multicolor_H57799_01_standard_vovikk.jpg",
      "stars": 4,
      "visible": true,
      "category": "Balon",
  },
  {
      "id": "b3aec9cb-6f1b-4bed-83e3-7d4ab9669f9a",
      "name": "JERSEY LOCAL SELECCIÓN CROACIA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605810/croacialocal_1024x1024_dojebq.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "c6a6c61e-6af7-439b-8af8-687c7794b510",
      "name": "BALÓN UNIFORIA FINALE LEAGUE",
      "price": 569,
      "detail": "Este producto está agotado. Suscríbete a nuestra newsletter y entérate antes que nadie de los próximos lanzamientos.",
      "size-stock": [
        {"size" : "1", "stock":20},
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665524741/Balon_Uniforia_Finale_League_Plata_FT8305_01_standard_ht9tyf.jpg",
      "stars": 5,
      "visible": true,
      "category": "Balon",
  },
  {
      "id": "ec27902f-67c1-4472-82dd-5270a65181a0",
      "name": "JERSEY VISITANTE SELECCIÓN CROACIA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605831/croaciavisi_1024x1024_afgaou.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "51ed5e6a-32a1-4494-b9d8-afd151d83f3a",
      "name": "JERSEY VISITANTE SELECCIÓN PORTUGAL 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665604655/portugalvisi_1024x1024_k7rhel.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "f0b56f6d-7189-4153-b818-2cc9bfbc7dc6",
      "name": "JERSEY UNIFORME DE LOCAL BÉLGICA 22",
      "price": 1799,
      "detail": "Ilumina el evento de fútbol más importante. Con llamas rojas y amarillas envolviendo sus mangas negras, este jersey de local de Bélgica se inspira en el apodo de los Diablos Rojos. Su tejido con tecnología de absorción AEROREADY y los paneles de malla mantienen a los hinchas secos en los momentos más intensos en la cancha. El logo de las 3 Franjas de adidas en el pecho le confiere un look fresco y se combina con una versión tejida del escudo de Bélgica.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665517741/Jersey_Uniforme_de_Local_Belgica_22_Rojo_HD9412_21_model_aknlca.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "b5af751e-950d-4310-a921-140f96e389a9",
      "name": "CALZADO DE FÚTBOL X SPEEDPORTAL.3 TERRENO FIRME",
      "price": 1999,
      "detail": "Desata tu velocidad multidimensional con adidas X Speedportal. Los tacos de antepié adicionales en la suela ligera de este calzado de fútbol adidas te permiten reaccionar con rapidez en el terreno firme. El exterior textil revestido suave incluye un cuello de sujeción de tejido plano y un refuerzo de talón externo en TPU para mantenerte firme en cada movimiento.",
      "size-stock": [
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
        {"size" : "6", "stock":20},
        {"size" : "7", "stock":20},
        {"size" : "8", "stock":20},
        {"size" : "9", "stock":20},
        {"size" : "10", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665524550/Calzado_de_Futbol_X_Speedportal.3_Terreno_Firme_Azul_GW8456_22_model_csrefk.jpg",
      "stars": 5,
      "visible": true,
      "category": "Calzado",
  },
  {
      "id": "3a092268-cda7-46d9-8d1c-ad251bffdeaa",
      "name": "JERSEY TERCERO SELECCIÓN CANADA 22",
      "price": 1799,
      "detail": "JERSEY TERCERO",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665603335/cNADAE_1024x1024_lylzyo.png",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "dfa5dd79-9075-4bc9-a43f-248d9900f0e3",
      "name": "JERSEY LOCAL SELECCIÓN SENEGAL 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596174/NZSTZNRE4VDLZPJSRHMKEOV4PY_kc2fmo.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "78c23fdd-97ac-4d6f-82c5-a6e4878dc6fa",
      "name": "JERSEY LOCAL SELECCIÓN AUSTRALIA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605472/australiaaa_1024x1024_ypivys.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "f494e3eb-8c47-4ae0-b26c-3c1b854d502b",
      "name": "JERSEY VISITANTE SELECCIÓN ECUADOR 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665594885/MK4FDLCVZFABFBSKCUBPG7U5QI_l1xqii.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "ba44d2b4-898c-44ef-afe2-6606cd6b919a",
      "name": "JERSEY VISITANTE SELECCIÓN POLONIA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665600517/poloniavisi_1024x1024_ktph0u.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "2c427246-a6fc-4f99-9f05-477d04b85513",
      "name": "JERSEY VISITANTE ARGENTINA 22",
      "price": 1799,
      "detail": "Este jersey adidas visitante de Argentina impulsa el orgullo nacional y la búsqueda de un mundo más justo. Presenta un color morado que representa la igualdad de género y un potente estampado inspirado en el Sol de Mayo presente en su bandera nacional. Creado para aportar comodidad a los seguidores, su tejido transpirable AEROREADY mantiene la piel fresca y seca. El escudo cosido en el pecho remata este look deportivo.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665517223/Jersey_Visitante_Nino_Argentina_22_Azul_HF1489_01_laydown_cconj8.jpg",
      "stars": 3,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "0daf9167-a3d0-4fa9-b09b-9d293c65f656",
      "name": "SHORTS UNIFORME DE LOCAL JAPÓN 22",
      "price": 1099,
      "detail": "Parte de un llamativo uniforme de local de Japón dominado por cuervos de origami. Estos shorts de fútbol adidas te envuelven con comodidad gracias a su tejido suave con tecnología de absorción AEROREADY. Lucen el escudo de la selección tejido para demostrar la fuerza de tu amor.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665529727/Shorts_Uniforme_de_Local_Japon_22_Blanco_HF1850_21_model_joqers.jpg",
      "stars": 5,
      "visible": true,
      "category": "Short",
  },
  {
      "id": "9e292a08-74e4-4680-ac11-dba8249592f9",
      "name": "JERSEY VISITANTE SELECCIÓN DINAMARCA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665600774/aaaadiannarc_1024x1024_gbfhod.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "ce7db420-cf29-4581-b4e2-71f36ac05bec",
      "name": "JERSEY UNIFORME DE VISITANTE BÉLGICA 22",
      "price": 1799,
      "detail": "Prepárate para destacar en el mayor escenario del fútbol internacional. El nuevo jersey de visitante adidas para los Diablos Rojos de Bélgica está inspirado en los fuegos artificiales de Tomorrowland. Una verdadera declaración de amor, como también se refleja en la parte exterior trasera del cuello con la inscripción LOVE y el logo de Tomorrowland. Diseñado para hinchas de fútbol y festivales de todos los rincones del mundo, este jersey incorpora tecnología de absorción AEROREADY.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665517786/Jersey_Uniforme_de_Visitante_Belgica_22_Blanco_HK5034_21_model_ksybih.jpg",
      "stars": 4,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "8026dcb9-483d-43ea-a4a8-6692b6a7aa01",
      "name": "JERSEY VISITANTE SELECCIÓN GHANA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596193/G6RFRDXWBZBLVOJTDGJBHYQMYM_gnqy6k.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "cd10f841-a8d3-45ba-bf0e-6c1cc60c8ec4",
      "name": "JERSEY LOCAL SELECCIÓN CAMERUN 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665611993/camiseta-le-coq-sportif-camerun-primera-equipacion-world-cup-2022-verde-0_duspbw.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "b84856c4-139c-4e56-b85e-7db33e667284",
      "name": "JERSEY LOCAL SELECCIÓN PORTUGAL 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665604631/portugal_a3355dd1-0871-426b-a8c8-e3bc7dbc9094_1024x1024_kf50zz.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "feacf066-bacf-4c83-add0-2dbfc0d9e9a5",
      "name": "SHORTS UNIFORME DE LOCAL ESPAÑA 22",
      "price": 1099,
      "detail": "Clásicos en todos los sentidos, estos shorts de fútbol adidas hacen parte del uniforme de local de España. Lucen los icónicos colores del país, el logo de las 3 Franjas y el escudo actualizado en la pierna. La tecnología AEROREADY mantiene tu cuerpo seco en la cancha y en los momentos de descanso en la tribuna.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665529441/Shorts_Uniforme_de_Local_Espana_22_Azul_HE2022_21_model_cgxczu.jpg",
      "stars": 3,
      "visible": true,
      "category": "Short",
  },
  {
      "id": "67ea8c8f-370b-4063-9bff-56de478a5342",
      "name": "JERSEY VISITANTE SELECCIÓN PAISES BAJOS 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665599294/holandavisi_4ef591a6-5769-4f9f-9a66-34bb1e8f1a24_1024x1024_mpwvfz.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "d3ca99d4-a666-42ef-a68a-1931c9d11c2d",
      "name": "JERSEY LOCAL SELECCIÓN INGLATERRA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665604335/inglaterralocal_1024x1024_bukmvn.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "427dcd7d-1be1-4efe-9da0-cf1633bbe76d",
      "name": "JERSEY VISITANTE SELECCIÓN AUSTRALIA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605486/australiaaa.visi_1024x1024_vrzal4.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "486846e7-4a1f-49ff-864d-b3d613a552fa",
      "name": "JERSEY LOCAL SELECCIÓN PAISES BAJOS 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665599279/holandalocal_1024x1024_qlrvg4.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "f39eba72-75db-4f87-88ec-57335d9b0e55",
      "name": "JERSEY VISITANTE SELECCIÓN TUNEZ 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665611382/j12p9n4rtuorymlkyntj.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "7681018b-f5b8-4202-ad50-1fafcdbcaa47",
      "name": "CALZADO DE FÚTBOL PREDATOR EDGE.1 PASTO SINTÉTICO",
      "price": 4599,
      "detail": "Da un giro a lo ordinario para encontrar tus límites. Introduce una nueva faceta de tu juego con este calzado de fútbol de pasto sintético adidas Predator. Sobre una mediasuela Bounce flexible, su exterior Zone Skin incluye secciones acanaladas discretas, cada una de las cuales se destaca en un tipo diferente de contacto con el balón. El cuello flexible de adidas PRIMEKNIT sujeta el pie mientras tú dominas la cancha.",
      "size-stock": [
        {"size" : "3", "stock":20},
        {"size" : "4", "stock":20},
        {"size" : "5", "stock":20},
        {"size" : "6", "stock":20},
        {"size" : "7", "stock":20},
        {"size" : "8", "stock":20},
        {"size" : "9", "stock":20},
        {"size" : "10", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665524590/Calzado_de_Futbol_Predator_Edge.1_Pasto_Sintetico_Blanco_GZ6101_22_model_nxblfb.jpg",
      "stars": 4,
      "visible": true,
      "category": "Calzado",
  },
  {
      "id": "04993cfe-b4b1-4b00-8ce5-c9cae74661a8",
      "name": "JERSEY UNIFORME DE LOCAL ESPAÑA 22",
      "price": 1499,
      "detail": "Un país unido. Inspirado en el distintivo ADN futbolístico de España, este jersey de local atemporal para jóvenes está dominado por los famosos colores rojos del equipo. En el pecho, versiones tejidas del escudo actualizado de la Selección de España y las 3 Franjas de adidas irradian orgullo. Incorpora tecnología de absorción AEROREADY que se encarga del sudor bajo la superficie para mantener a los hinchas cómodos mientras siguen la acción en la cancha.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665517283/Jersey_Uniforme_de_Local_Espana_22_Rojo_HF1408_01_laydown_enu6zd.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "a0c5c02b-cc7b-4ce2-aab6-74fffaaec5d5",
      "name": "JERSEY VISITANTE SELECCIÓN SUIZA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665598062/KYU7SH7MRNB7JKA6D2OKEWXOBM_jlehdh.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "5b0240b7-1168-4a95-9efe-9a33e98744fa",
      "name": "JERSEY VISITANTE SELECCIÓN QATAR 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665602103/qatarvis_1024x1024_p5qp3v.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "2dd6ed41-f8c2-457d-a83a-f399261bdce5",
      "name": "JERSEY ICON ALEMANIA",
      "price": 1699,
      "detail": "Luciendo los colores de la bandera nacional, los estampados adidas Equipment se destacan en los costados de este jersey de fútbol de Alemania. Parte de una colección que reinterpreta algo del estilo de los 90, está confeccionado en un ajuste holgado para brindar comodidad en todo momento. Luciendo esas envidiadas estrellas, el escudo del equipo ubicado en el centro le da un toque retro.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665517415/Jersey_Icon_Alemania_Blanco_HS5941_01_laydown_ocegf2.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "b7ac7b39-67ee-4537-bade-8b5c0ebf83d6",
      "name": "JERSEY LOCAL SELECCIÓN CANADA 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665603274/Canada2021StadiumHome_1800x1800_a81d8014-b481-4b77-9fd1-cf7950185d29_1024x1024_kjfspd.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "a6d45841-af20-4c37-8267-63a8081b116c",
      "name": "JERSEY VISITANTE SELECCIÓN CAMERUN 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665612026/jd_527846_b_720x_zfrlby.png",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "b5aded27-4f16-4ea1-84fa-3bc12f7e58f9",
      "name": "JERSEY VISITANTE SELECCIÓN COSTA RICA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665610762/Camisetas-Costa-Rica-Segunda-Equipaci_C3_B3nes-2022_avnxte.png",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "8db5f75d-8d48-4b92-ac43-86013541f626",
      "name": "JERSEY VISITANTE SELECCIÓN GALES 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665612436/wales-2022-world-cup-home-and-away-kits-12_xp5f6v.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "da9aa538-649d-4fd8-b40d-b6b943e636f7",
      "name": "JERSEY VISITANTE SELECCIÓN JAPÓN 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596466/H4OSQQ3ZERAKFBKLYHHOJU2JKI_htbsnu.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "a62c4b48-1d11-4c58-8111-76de1c711128",
      "name": "JERSEY VISITANTE SELECCIÓN FRANCIA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665604076/franciavisi_46bbf3b5-6add-4ec2-aca0-80f46c3cb27c_1024x1024_dhhnaf.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "b16b096d-93dc-4529-aab0-a0019698f30f",
      "name": "JERSEY VISITANTE SELECCIÓN COREA DEL SUR 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665605130/coreavisi_1024x1024_u4upxb.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "a57e616f-7547-458c-82b0-07a26f8a0970",
      "name": "JERSEY VISITANTE SELECCIÓN INGLATERRA 22",
      "price": 1799,
      "detail": "JERSEY VISITANTE",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665604358/inglaterravisi_937ea5b0-996e-4438-a179-e4028a435394_1024x1024_tcmyyo.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "ea0b4279-018d-4c04-9a8e-394f50e7305e",
      "name": "JERSEY LOCAL SELECCIÓN JAPÓN 22",
      "price": 1799,
      "detail": "JERSEY LOCAL",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665596446/VIMSP4OEONBD7OUTBH6XLLI434_io4sgw.jpg",
      "stars": 5,
      "visible": true,
      "category": "Jersey",
  },
  {
      "id": "cafab12e-71a3-42d9-9fa0-177306d9191e",
      "name": "SHORTS UNIFORME DE LOCAL ALEMANIA 22",
      "price": 1099,
      "detail": "Parte del uniforme de local de la Selección de Alemania, inspirado en el ADN. Hechos con tejido suave con tecnología de absorción AEROREADY, estos shorts de fútbol adidas te mantienen cómodo sin importar si estás corriendo por la cancha o siguiendo a tus héroes. El escudo del equipo tejido tiene la última palabra y las cuatro estrellas que tanto han costado conseguir.",
      "size-stock": [
        {"size" : "S", "stock":20},
        {"size" : "M", "stock":20},
        {"size" : "L", "stock":20},
        {"size" : "XL", "stock":20},
      ],
      "image": "https://res.cloudinary.com/ddl3snuoe/image/upload/v1665529527/Shorts_Uniforme_de_Local_Alemania_22_Negro_HJ9605_21_model_bzu6zh.jpg",
      "stars": 4,
      "visible": true,
      "category": "Short",
  }
];

module.exports= jsonProducts;